@api=http://localhost:5000

###
POST {{api}}/tournaments/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImVtYWlsIjoibWFrc3Rlc2xlbmtvOTI0QGdtYWlsLmNvbSIsIm5hbWUiOiJSb290VVNlciIsImljb24iOiIiLCJpYXQiOjE2NTgxMzc5NjAsImV4cCI6MTY1ODIyNDM2MH0.G8nMVSiUqpE5zDgtOII9Ol7T82X5MK6fW9DbqAteuUE

{
    "title":"Tournament 1",
    "ownerEmail":"maksteslenko924@gmail.com",
    "format":"Single Elimination",
    "gameFormat":"5v5",
    "game":"dota"
}

###
GET {{api}}/tournaments/get/Dota
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImVtYWlsIjoibWFrc3Rlc2xlbmtvOTI0QGdtYWlsLmNvbSIsIm5hbWUiOiJSb290VVNlciIsImljb24iOiIiLCJpYXQiOjE2NTIzODA1MjEsImV4cCI6MTY1MjQ2NjkyMX0.tlLeVyg3bzMmVB_q-pMDJ_sgE3vMpF-vYhe1g1SITPU

###
GET {{api}}/tournaments/getById/129
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImVtYWlsIjoibWFrc3Rlc2xlbmtvOTI0QGdtYWlsLmNvbSIsIm5hbWUiOiJSb290VVNlciIsImljb24iOiIiLCJpYXQiOjE2NTUxMDk5MjcsImV4cCI6MTY1NTE5NjMyN30.4kmGnjrxXfAXshrh0olWonXLI4P1Eb-0z2O_1agGEXk

###
POST {{api}}/tournaments/update/132
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImVtYWlsIjoibWFrc3Rlc2xlbmtvOTI0QGdtYWlsLmNvbSIsIm5hbWUiOiJSb290VVNlciIsImljb24iOiIiLCJpYXQiOjE2NTQyNjMxOTgsImV4cCI6MTY1NDM0OTU5OH0.KpcTo_O-f4efJEvaoVs_wRMoiXARt9fxTpuhWVBugHM

{
    "field":"size",
    "value":"12"
}

### 
POST {{api}}/matches/update/round/1/130
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImVtYWlsIjoibWFrc3Rlc2xlbmtvOTI0QGdtYWlsLmNvbSIsIm5hbWUiOiJSb290VVNlciIsImljb24iOiIiLCJpYXQiOjE2NTQzNjM5MTMsImV4cCI6MTY1NDQ1MDMxM30.jeN-r0T5SEFHQAYLX66iAYfYyJzmICN9XOD1jaZGdQ0
{
    "field":"startAt",
    "value":"2022-06-13"
}

###
POST {{api}}/tournaments/getAll
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImVtYWlsIjoibWFrc3Rlc2xlbmtvOTI0QGdtYWlsLmNvbSIsIm5hbWUiOiJSb290VVNlciIsImljb24iOiIiLCJpYXQiOjE2NTQzNjM5MTMsImV4cCI6MTY1NDQ1MDMxM30.jeN-r0T5SEFHQAYLX66iAYfYyJzmICN9XOD1jaZGdQ0

{
    "game":"Dota",
    "accessType":"all",
    "search":"",
    "orderBy":"startAt"
}

###
POST {{api}}/tournaments/addCompetitor/132
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImVtYWlsIjoibWFrc3Rlc2xlbmtvOTI0QGdtYWlsLmNvbSIsIm5hbWUiOiJSb290VVNlciIsImljb24iOiIiLCJpYXQiOjE2NTUxMDk5MjcsImV4cCI6MTY1NTE5NjMyN30.4kmGnjrxXfAXshrh0olWonXLI4P1Eb-0z2O_1agGEXk

{
   "maxNumberRound":3
}

### 
DELETE {{api}}/tournaments/delete/130
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImVtYWlsIjoibWFrc3Rlc2xlbmtvOTI0QGdtYWlsLmNvbSIsIm5hbWUiOiJSb290VVNlciIsImljb24iOiIiLCJpYXQiOjE2NTc4ODY0MjAsImV4cCI6MTY1Nzk3MjgyMH0.K-0cBEY_upyVog7hzo7k15B0BR4bQ4iwJfVXjqzR7ds

###
POST {{api}}/tournaments/decodeInviteStr
Content-Type: application/json

{
    "token":"$2a$05$G/4JlmuEKBOk.3MdGaq2C.2wNeXp5Ov.ES1EogDa9FwRBLsclHr5e"
}
